In [15]:
import pandas as pd
import numpy as np
import matplotlib
import ast
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings('ignore')

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

#폰트 설정(없으면 영문으로 나옴)
try:
    font_path = [f for f in fm.findSystemFonts() if 'NanumGothic' in f or 'Malgun' in f or 'AppleGothic' in f]
    if font_path:
        plt.rcParams['font.family'] = fm.FontProperties(fname=font_path[0]).get_name()
    else:
        plt.rcParams['font.family'] = 'DejaVu Sans'
except:
    plt.rcParams['font.family'] = 'DejaVu Sans'

plt.rcParams['axes.unicode_minus'] = False

In [21]:
funnel = pd.read_csv('./funnel_instance.csv')
analysis = pd.read_csv('./funnel_instance_analysis.csv')

funnel_s = funnel[['customer_id', 'offer_id', 'instance_id', 'gap_to_view', 
            'gap_to_complete', 'gap_view_to_complete', 
            't_received', 't_viewed', 't_completed']
            ]

df = analysis.merge(
    funnel_s,
    on = ['customer_id', 'offer_id', 'instance_id'],
    how='left'
)
df.head(10)

,customer_id,offer_id,t_received_x,offer_type,instance_id,duration,t_expire,t_viewed_x,last_viewed,view_count,view_ambiguous,t_completed_x,last_completed,complete_count,comp_ambiguous,gap_to_view_x,gap_to_complete_x,is_viewed,is_completed,completed_without_prior_view,gap_view_to_complete_x,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,gender,age_group,income_group,join_year,join_month,join_cohort,gap_to_view_y,gap_to_complete_y,gap_view_to_complete_y,t_received_y,t_viewed_y,t_completed_y
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,576,discount,1,7.0,744.0,NaN,NaN,NaN,NaN,576.0,576.0,1.0,0.0,NaN,0.0,False,True,True,NaN,2.0,10.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04,NaN,0.0,NaN,576,NaN,576.0
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,336,informational,1,4.0,432.0,372.0,372.0,1.0,0.0,NaN,NaN,NaN,NaN,36.0,NaN,True,False,False,NaN,0.0,0.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04,36.0,NaN,NaN,336,372.0,NaN
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,168,informational,1,3.0,240.0,192.0,192.0,1.0,0.0,NaN,NaN,NaN,NaN,24.0,NaN,True,False,False,NaN,0.0,0.0,0.0,1.0,1.0,1.0,3.0,M,30대,5-7.5만,2017,4,2017-04,24.0,NaN,NaN,168,192.0,NaN
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,408,bogo,1,5.0,528.0,456.0,456.0,1.0,0.0,414.0,414.0,1.0,0.0,48.0,6.0,True,True,True,NaN,5.0,5.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04,48.0,6.0,NaN,408,456.0,414.0
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,504,discount,1,10.0,744.0,540.0,540.0,1.0,0.0,528.0,528.0,1.0,0.0,36.0,24.0,True,True,True,NaN,2.0,10.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04,36.0,24.0,NaN,504,540.0,528.0
5,00116118485d4dfda04fdbaba9a87b5c,f19421c1d4aa40978ebb69ca19b0e20d,168,bogo,1,5.0,288.0,216.0,216.0,1.0,0.0,NaN,NaN,NaN,NaN,48.0,NaN,True,False,False,NaN,5.0,5.0,1.0,1.0,1.0,1.0,4.0,Unknown,누락,누락,2018,4,2018-04,48.0,NaN,NaN,168,216.0,NaN
6,00116118485d4dfda04fdbaba9a87b5c,f19421c1d4aa40978ebb69ca19b0e20d,576,bogo,2,5.0,696.0,630.0,630.0,1.0,0.0,NaN,NaN,NaN,NaN,54.0,NaN,True,False,False,NaN,5.0,5.0,1.0,1.0,1.0,1.0,4.0,Unknown,누락,누락,2018,4,2018-04,54.0,NaN,NaN,576,630.0,NaN
7,0011e0d4e6b944f998e987f904e8c1e5,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,discount,1,10.0,648.0,432.0,432.0,1.0,0.0,576.0,576.0,1.0,0.0,24.0,168.0,True,True,False,144.0,5.0,20.0,1.0,1.0,0.0,0.0,2.0,O,40대,5-7.5만,2018,1,2018-01,24.0,168.0,144.0,408,432.0,576.0
8,0011e0d4e6b944f998e987f904e8c1e5,2298d6c36e964ae4a3e7e9706d1fb8c2,168,discount,1,7.0,336.0,186.0,186.0,1.0,0.0,252.0,252.0,1.0,0.0,18.0,84.0,True,True,False,66.0,3.0,7.0,1.0,1.0,1.0,1.0,4.0,O,40대,5-7.5만,2018,1,2018-01,18.0,84.0,66.0,168,186.0,252.0
9,0011e0d4e6b944f998e987f904e8c1e5,3f207df678b143eea3cee63160fa8bed,0,informational,1,4.0,96.0,6.0,6.0,1.0,0.0,NaN,NaN,NaN,NaN,6.0,NaN,True,False,False,NaN,0.0,0.0,1.0,1.0,1.0,0.0,3.0,O,40대,5-7.5만,2018,1,2018-01,6.0,NaN,NaN,0,6.0,NaN

In [20]:
df.columns

Index(['customer_id', 'offer_id', 't_received_x', 'offer_type', 'instance_id',
       'duration', 't_expire', 't_viewed_x', 'last_viewed', 'view_count',
       'view_ambiguous', 't_completed_x', 'last_completed', 'complete_count',
       'comp_ambiguous', 'gap_to_view_x', 'gap_to_complete_x', 'is_viewed',
       'is_completed', 'completed_without_prior_view',
       'gap_view_to_complete_x', 'reward', 'difficulty', 'ch_web', 'ch_email',
       'ch_mobile', 'ch_social', 'channel_count', 'gender', 'age_group',
       'income_group', 'join_year', 'join_month', 'join_cohort',
       'gap_to_view_y', 'gap_to_complete_y', 'gap_view_to_complete_y',
       't_received_y', 't_viewed_y', 't_completed_y'],
      dtype='str')

In [18]:
cols_to_check = ['t_received', 't_viewed', 't_completed', 'gap_to_view', 'gap_to_complete', 'gap_view_to_complete']

{col: col in df.columns for col in cols_to_check}

{'t_received': False,
 't_viewed': False,
 't_completed': False,
 'gap_to_view': False,
 'gap_to_complete': False,
 'gap_view_to_complete': False}

In [19]:
df[['gap_to_view', 'gap_to_complete', 'gap_view_to_complete']].describe()
#얼마나 빠르게 보고 / 얼마나 빠르게 행동하며 / 얼마나 빠르게 구매완료하는가
#24 정도에 인지하고 / 61 정도에 행동하며 / 인지 후 구매는 51 정도에 한다

KeyError: "None of [Index(['gap_to_view', 'gap_to_complete', 'gap_view_to_complete'], dtype='str')] are in the [columns]"

In [ ]:
valid_df = df[
    (df['is_viewed']==True)&
    (df['is_completed']==True)&
    (df['completed_without_prior_view']==False)
].copy()

valid_df.head(10)

,customer_id,offer_id,t_received,offer_type,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,is_viewed,is_completed,completed_without_prior_view,gap_view_to_complete
7,0011e0d4e6b944f998e987f904e8c1e5,0b1e1539f2cc45b7b9fa7c272da2e1d7,408,discount,1,10.0,648.0,432.0,432.0,1.0,0.0,576.0,576.0,1.0,0.0,24.0,168.0,True,True,False,144.0
8,0011e0d4e6b944f998e987f904e8c1e5,2298d6c36e964ae4a3e7e9706d1fb8c2,168,discount,1,7.0,336.0,186.0,186.0,1.0,0.0,252.0,252.0,1.0,0.0,18.0,84.0,True,True,False,66.0
11,0011e0d4e6b944f998e987f904e8c1e5,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,bogo,1,7.0,672.0,516.0,516.0,1.0,0.0,576.0,576.0,1.0,0.0,12.0,72.0,True,True,False,60.0
12,0020c2b971eb4e9188eac86d93036a77,4d5c57ea9a6940dd891ad53e9dbe8da0,408,bogo,1,5.0,528.0,426.0,426.0,1.0,0.0,510.0,510.0,1.0,0.0,18.0,102.0,True,True,False,84.0
15,0020c2b971eb4e9188eac86d93036a77,fafdcd668e3743c1bb461111dcafc2a4,0,discount,1,10.0,240.0,12.0,12.0,1.0,0.0,54.0,54.0,1.0,0.0,12.0,54.0,True,True,False,42.0
17,0020ccbbb6d84e358d3414a3ff76cffd,2298d6c36e964ae4a3e7e9706d1fb8c2,168,discount,1,7.0,336.0,168.0,168.0,1.0,0.0,222.0,222.0,1.0,0.0,0.0,54.0,True,True,False,54.0
19,0020ccbbb6d84e358d3414a3ff76cffd,9b98b8c7a33c4b65b9aebfe6a799e6d9,504,bogo,1,7.0,672.0,582.0,582.0,1.0,0.0,600.0,600.0,1.0,0.0,78.0,96.0,True,True,False,18.0
20,0020ccbbb6d84e358d3414a3ff76cffd,f19421c1d4aa40978ebb69ca19b0e20d,336,bogo,1,5.0,456.0,348.0,348.0,1.0,0.0,378.0,378.0,1.0,0.0,12.0,42.0,True,True,False,30.0
24,003d66b6608740288d6cc97a6903f4f0,fafdcd668e3743c1bb461111dcafc2a4,168,discount,1,10.0,408.0,300.0,300.0,1.0,0.0,384.0,384.0,1.0,0.0,132.0,216.0,True,True,False,84.0
25,003d66b6608740288d6cc97a6903f4f0,fafdcd668e3743c1bb461111dcafc2a4,408,discount,2,10.0,648.0,420.0,420.0,1.0,0.0,504.0,504.0,1.0,0.0,12.0,96.0,True,True,False,84.0

In [ ]:
gap_seg = (
    valid_df
    .groupby(['gender', 'age_group', 'income_group'])
    .agg(
        avg_gap = ('gap_view_to_complete', 'mean'),
        median_gap = ('gap_view_to_complete', 'median'),
        n = ('customer_id', 'count')
    )
    .reset_index()
)

gap_seg.sort_values('avg_gap').head(10)

KeyError: 'gender'